version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: demo-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quiz
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://demo-db:3306/quiz
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
